/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nabook.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BookOrder service. Represents a row in the &quot;nab_BookOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nabook.model.impl.BookOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nabook.model.impl.BookOrderImpl}.
 * </p>
 *
 * @author phantoan
 * @see BookOrder
 * @see com.nabook.model.impl.BookOrderImpl
 * @see com.nabook.model.impl.BookOrderModelImpl
 * @generated
 */
@ProviderType
public interface BookOrderModel extends BaseModel<BookOrder>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book order model instance should use the {@link BookOrder} interface instead.
	 */

	/**
	 * Returns the primary key of this book order.
	 *
	 * @return the primary key of this book order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this book order.
	 *
	 * @param primaryKey the primary key of this book order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this book order.
	 *
	 * @return the uuid of this book order
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this book order.
	 *
	 * @param uuid the uuid of this book order
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the book order ID of this book order.
	 *
	 * @return the book order ID of this book order
	 */
	public long getBookOrderId();

	/**
	 * Sets the book order ID of this book order.
	 *
	 * @param bookOrderId the book order ID of this book order
	 */
	public void setBookOrderId(long bookOrderId);

	/**
	 * Returns the group ID of this book order.
	 *
	 * @return the group ID of this book order
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this book order.
	 *
	 * @param groupId the group ID of this book order
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this book order.
	 *
	 * @return the company ID of this book order
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this book order.
	 *
	 * @param companyId the company ID of this book order
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this book order.
	 *
	 * @return the create date of this book order
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this book order.
	 *
	 * @param createDate the create date of this book order
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this book order.
	 *
	 * @return the modified date of this book order
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this book order.
	 *
	 * @param modifiedDate the modified date of this book order
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this book order.
	 *
	 * @return the user ID of this book order
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this book order.
	 *
	 * @param userId the user ID of this book order
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this book order.
	 *
	 * @return the user uuid of this book order
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this book order.
	 *
	 * @param userUuid the user uuid of this book order
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this book order.
	 *
	 * @return the user name of this book order
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this book order.
	 *
	 * @param userName the user name of this book order
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the status of this book order.
	 *
	 * @return the status of this book order
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this book order.
	 *
	 * @param status the status of this book order
	 */
	public void setStatus(String status);

	/**
	 * Returns the billing name of this book order.
	 *
	 * @return the billing name of this book order
	 */
	@AutoEscape
	public String getBillingName();

	/**
	 * Sets the billing name of this book order.
	 *
	 * @param billingName the billing name of this book order
	 */
	public void setBillingName(String billingName);

	/**
	 * Returns the billing country of this book order.
	 *
	 * @return the billing country of this book order
	 */
	@AutoEscape
	public String getBillingCountry();

	/**
	 * Sets the billing country of this book order.
	 *
	 * @param billingCountry the billing country of this book order
	 */
	public void setBillingCountry(String billingCountry);

	/**
	 * Returns the billing city of this book order.
	 *
	 * @return the billing city of this book order
	 */
	@AutoEscape
	public String getBillingCity();

	/**
	 * Sets the billing city of this book order.
	 *
	 * @param billingCity the billing city of this book order
	 */
	public void setBillingCity(String billingCity);

	/**
	 * Returns the billing prefecture of this book order.
	 *
	 * @return the billing prefecture of this book order
	 */
	@AutoEscape
	public String getBillingPrefecture();

	/**
	 * Sets the billing prefecture of this book order.
	 *
	 * @param billingPrefecture the billing prefecture of this book order
	 */
	public void setBillingPrefecture(String billingPrefecture);

	/**
	 * Returns the billing street of this book order.
	 *
	 * @return the billing street of this book order
	 */
	@AutoEscape
	public String getBillingStreet();

	/**
	 * Sets the billing street of this book order.
	 *
	 * @param billingStreet the billing street of this book order
	 */
	public void setBillingStreet(String billingStreet);

	/**
	 * Returns the billing zip of this book order.
	 *
	 * @return the billing zip of this book order
	 */
	@AutoEscape
	public String getBillingZip();

	/**
	 * Sets the billing zip of this book order.
	 *
	 * @param billingZip the billing zip of this book order
	 */
	public void setBillingZip(String billingZip);

	/**
	 * Returns the ship to billing of this book order.
	 *
	 * @return the ship to billing of this book order
	 */
	public boolean getShipToBilling();

	/**
	 * Returns <code>true</code> if this book order is ship to billing.
	 *
	 * @return <code>true</code> if this book order is ship to billing; <code>false</code> otherwise
	 */
	public boolean isShipToBilling();

	/**
	 * Sets whether this book order is ship to billing.
	 *
	 * @param shipToBilling the ship to billing of this book order
	 */
	public void setShipToBilling(boolean shipToBilling);

	/**
	 * Returns the shipping name of this book order.
	 *
	 * @return the shipping name of this book order
	 */
	@AutoEscape
	public String getShippingName();

	/**
	 * Sets the shipping name of this book order.
	 *
	 * @param shippingName the shipping name of this book order
	 */
	public void setShippingName(String shippingName);

	/**
	 * Returns the shipping country of this book order.
	 *
	 * @return the shipping country of this book order
	 */
	@AutoEscape
	public String getShippingCountry();

	/**
	 * Sets the shipping country of this book order.
	 *
	 * @param shippingCountry the shipping country of this book order
	 */
	public void setShippingCountry(String shippingCountry);

	/**
	 * Returns the shipping city of this book order.
	 *
	 * @return the shipping city of this book order
	 */
	@AutoEscape
	public String getShippingCity();

	/**
	 * Sets the shipping city of this book order.
	 *
	 * @param shippingCity the shipping city of this book order
	 */
	public void setShippingCity(String shippingCity);

	/**
	 * Returns the shipping prefecture of this book order.
	 *
	 * @return the shipping prefecture of this book order
	 */
	@AutoEscape
	public String getShippingPrefecture();

	/**
	 * Sets the shipping prefecture of this book order.
	 *
	 * @param shippingPrefecture the shipping prefecture of this book order
	 */
	public void setShippingPrefecture(String shippingPrefecture);

	/**
	 * Returns the shipping street of this book order.
	 *
	 * @return the shipping street of this book order
	 */
	@AutoEscape
	public String getShippingStreet();

	/**
	 * Sets the shipping street of this book order.
	 *
	 * @param shippingStreet the shipping street of this book order
	 */
	public void setShippingStreet(String shippingStreet);

	/**
	 * Returns the shipping zip of this book order.
	 *
	 * @return the shipping zip of this book order
	 */
	@AutoEscape
	public String getShippingZip();

	/**
	 * Sets the shipping zip of this book order.
	 *
	 * @param shippingZip the shipping zip of this book order
	 */
	public void setShippingZip(String shippingZip);

	/**
	 * Returns the phone of this book order.
	 *
	 * @return the phone of this book order
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this book order.
	 *
	 * @param phone the phone of this book order
	 */
	public void setPhone(String phone);

	/**
	 * Returns the total of this book order.
	 *
	 * @return the total of this book order
	 */
	@AutoEscape
	public String getTotal();

	/**
	 * Sets the total of this book order.
	 *
	 * @param total the total of this book order
	 */
	public void setTotal(String total);

	/**
	 * Returns the tax of this book order.
	 *
	 * @return the tax of this book order
	 */
	public int getTax();

	/**
	 * Sets the tax of this book order.
	 *
	 * @param tax the tax of this book order
	 */
	public void setTax(int tax);

	/**
	 * Returns the discount of this book order.
	 *
	 * @return the discount of this book order
	 */
	public int getDiscount();

	/**
	 * Sets the discount of this book order.
	 *
	 * @param discount the discount of this book order
	 */
	public void setDiscount(int discount);

	/**
	 * Returns the shipfee of this book order.
	 *
	 * @return the shipfee of this book order
	 */
	@AutoEscape
	public String getShipfee();

	/**
	 * Sets the shipfee of this book order.
	 *
	 * @param shipfee the shipfee of this book order
	 */
	public void setShipfee(String shipfee);

	/**
	 * Returns the payment of this book order.
	 *
	 * @return the payment of this book order
	 */
	@AutoEscape
	public String getPayment();

	/**
	 * Sets the payment of this book order.
	 *
	 * @param payment the payment of this book order
	 */
	public void setPayment(String payment);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BookOrder bookOrder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BookOrder> toCacheModel();

	@Override
	public BookOrder toEscapedModel();

	@Override
	public BookOrder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}