/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nabook.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Cart service. Represents a row in the &quot;nab_Cart&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nabook.model.impl.CartModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nabook.model.impl.CartImpl}.
 * </p>
 *
 * @author phantoan
 * @see Cart
 * @see com.nabook.model.impl.CartImpl
 * @see com.nabook.model.impl.CartModelImpl
 * @generated
 */
@ProviderType
public interface CartModel extends BaseModel<Cart>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cart model instance should use the {@link Cart} interface instead.
	 */

	/**
	 * Returns the primary key of this cart.
	 *
	 * @return the primary key of this cart
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cart.
	 *
	 * @param primaryKey the primary key of this cart
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cart.
	 *
	 * @return the uuid of this cart
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this cart.
	 *
	 * @param uuid the uuid of this cart
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the cart ID of this cart.
	 *
	 * @return the cart ID of this cart
	 */
	public long getCartId();

	/**
	 * Sets the cart ID of this cart.
	 *
	 * @param cartId the cart ID of this cart
	 */
	public void setCartId(long cartId);

	/**
	 * Returns the group ID of this cart.
	 *
	 * @return the group ID of this cart
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this cart.
	 *
	 * @param groupId the group ID of this cart
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this cart.
	 *
	 * @return the company ID of this cart
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cart.
	 *
	 * @param companyId the company ID of this cart
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this cart.
	 *
	 * @return the create date of this cart
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cart.
	 *
	 * @param createDate the create date of this cart
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cart.
	 *
	 * @return the modified date of this cart
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cart.
	 *
	 * @param modifiedDate the modified date of this cart
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this cart.
	 *
	 * @return the user ID of this cart
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this cart.
	 *
	 * @param userId the user ID of this cart
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cart.
	 *
	 * @return the user uuid of this cart
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cart.
	 *
	 * @param userUuid the user uuid of this cart
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cart.
	 *
	 * @return the user name of this cart
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this cart.
	 *
	 * @param userName the user name of this cart
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the book ID of this cart.
	 *
	 * @return the book ID of this cart
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this cart.
	 *
	 * @param bookId the book ID of this cart
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the quantity of this cart.
	 *
	 * @return the quantity of this cart
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this cart.
	 *
	 * @param quantity the quantity of this cart
	 */
	public void setQuantity(int quantity);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Cart cart);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Cart> toCacheModel();

	@Override
	public Cart toEscapedModel();

	@Override
	public Cart toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}